# docker-compose.yml
services:
  cockroachdb:
    image: cockroachdb/cockroach:latest-v23.1
    command: start-single-node --insecure
    restart: 'unless-stopped'
    volumes:
      - data:/cockroach/cockroach-data
    ports:
      - '26257:26257'
      - '8080:8080'

  # Build TypeScript match handler
  nakama-builder:
    build:
      context: ./typescript
      dockerfile: Dockerfile
    command: sh -c "npm run build && tail -f /dev/null"
    volumes:
      - matchcode:/app/dist
    healthcheck:
      test: ['CMD', 'sh', '-c', 'test -f /app/dist/index.js']
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 5s

  nakama:
    image: registry.heroiclabs.com/heroiclabs/nakama:3.20.0
    entrypoint:
      - '/bin/sh'
      - '-ec'
      - /nakama/nakama migrate up --database.address root@cockroachdb:26257 && exec /nakama/nakama --name nakama1 --database.address root@cockroachdb:26257 --logger.level DEBUG --runtime.path /nakama/data/modules --runtime.js_entrypoint index.js
    restart: 'unless-stopped'
    links:
      - 'cockroachdb:db'
    depends_on:
      cockroachdb:
        condition: service_started
      nakama-builder:
        condition: service_healthy
    volumes:
      - matchcode:/nakama/data/modules:ro
    ports:
      - '7349:7349'
      - '7350:7350'
      - '7351:7351'
volumes:
  data:
  matchcode:
